config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :users, only: :new
  resources :trails, only: :show
  resources :excuses, only: :index

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/dashboard', to: 'users#show', as: 'dashboard'
  get "/signout" => "sessions#destroy", :as => :signout
  get "/search", to: 'locations#show'
  get "/location", to: 'trails#index'
  get "/alternative", to: 'alternative_activities#index'

end

app/models/activity.rb
class Activity

  def self.activities  
    [
      "amusement_park",
      "aquarium",
      "art_gallery",
      "atm",
      "bakery",
      "bank",
      "bar",
      "beauty_salon",
      "bicycle_store",
      "book_store",
      "bowling_alley",
      "cafe",
      "casino",
      "convenience_store",
      "department_store",
      "gym",
      "hair_care",
      "library",
      "liquor_store",
      "lodging",
      "movie_theater",
      "museum",
      "night_club",
      "pet_store",
      "restaurant",
      "shoe_store",
      "shopping_mall",
      "spa",
      "stadium",
      "zoo"
    ]
  end

end

app/models/alternative_activity.rb
class AlternativeActivity
  attr_reader :services

  def self.services(location, rankby, type)
    @services = AlternativeActivityService.new(location, rankby, type)
  end

  def self.alternative_activity_search(location, rankby, type)
    services(location, rankby, type).find_activities_by_type
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excuse.rb
class Excuse

  def self.excuse_list
    ["My wife hid all my shoes from me.",
      "My neighbor said if he saw me come out of the house he’d kill me.",
      "The city dumped a huge pile of sand in my driveway.",
      "I got stuck playing Pokemon GO.",
      "I stayed home in solidarity to all the kids working in sweatshops in China.",
      "I had to meet with my son’s parole officer.",
      "My electricity went off and my alarm clock said it was 12:00 am when it was really 7:00 am.",
      "My wife straightened up the house and I couldn’t find my keys.",
      "I was up all night with a colicky baby.",
      "We got snowed in.",
      "Our albino tree frog got out of his cage.",
      "Somebody left the gate open and the cows got out.",
      "The landlord changed the lock on the garage and I couldn’t get access to my car.",
      "A huge tree fell in the driveway and I couldn’t get out.",
      "My wife got lost in a snowstorm and I had to go find her.",
      "A police helicopter kept flying over my house and announcing things like don’t come out  -  stay inside your house."]
  end

end

app/models/search.rb
class Search < OpenStruct
  attr_reader :services

  def self.services
    @services = SearchService.new
  end

  def self.search_by_current_location
    services.search_by_current_location
  end

  def self.search_by_input_location(city, state)
    services.search_by_input_location(city, state)
  end
end

app/models/states.rb
class States

  def self.states_list
    ["Arizona", "Arkansas", "California", "Colorado", "Florida",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
    "Louisiana", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Montana", "Nebraska", "New Mexico", "New York", "North Carolina", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "Tennessee", "Texas", "Utah", "Virginia", "Washington", "West Virginia",
     "Wisconsin", "Wyoming"]
  end

end

app/models/trail.rb
class Trail < OpenStruct
  attr_reader :services

  def self.services
    @services = TrailService.new
  end

  def self.all_hiking_locations
    location_hashes = services.all_hiking_locations
    location_hashes.places.map do |location_hash|
      Trail.new(location_hash)
    end
  end

  def self.formatted_locations_by_state(state)
    services.formatted_locations_by_state(state)
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :uid, :credentials
  validates_uniqueness_of :uid, :credentials


  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider    = auth["provider"]
      user.uid         = auth["uid"]
      user.name        = auth["info"]["name"]
      user.first_name  = auth["info"]["first_name"]
      user.last_name   = auth["info"]["last_name"]
      user.credentials = auth["credentials"]["token"]
      user.image       = auth["info"]["image"]
    end
  end

end

app/controllers/alternative_activities_controller.rb
class AlternativeActivitiesController < ApplicationController

  def index
    @alt_activities = AlternativeActivity.alternative_activity_search(params[:location], params[:rankby], params[:type])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/excuses_controller.rb
class ExcusesController < ApplicationController

  def index
    @excuses = Excuse.excuse_list
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    if params[:trail]
      @location = Search.search_by_input_location(params[:trail], params[:state])
    else
      @location = Search.search_by_current_location
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to dashboard_path, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    @trails = Trail.formatted_locations_by_state(params[:state])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    # @user = User.find(params[:id])
  end

  def new

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    look = Trail.all_hiking_locations
    # require "pry"; binding.pry
    trail_states = Trail.all_hiking_locations.map do |loc|
      loc.state
    end
    trail_states.delete("All")
    @trails = trail_states
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alternative_activities/index.html.erb
<% if @alt_activities.status == "ZERO_RESULTS" %>
<h1 class="search-header"> Womp Womp...No locations of that type found in the area. Try searching for something else to do:</h1>
<div class="center">
<%= form_tag("/alternative", method: "get") do %>
<%= select_tag 'type', options_for_select(Activity.activities), class:'form-control' %>
<%= hidden_field_tag 'location', params[:location] %>
<%= hidden_field_tag 'rankby', "distance" %><br>
<%= submit_tag("Let's Try Again!", class: 'btn-primary') %>
<% end %>
</div>

<% else %>

<h1 class="header"><%= @alt_activities.results.first.types.first.pluralize.capitalize %> near your location:</h1><br>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Google Places Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @alt_activities.results.each do |activity| %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.vicinity %></td>
      <td><%= activity.rating %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<div id="search-box">
  <div class="suggestions">
    <h1> Anything else you want to check out?</h1>
    <%= form_tag("/alternative", method: "get") do %>
    <%= select_tag 'type', options_for_select(Activity.activities), class:'form-control' %>
    <%= hidden_field_tag 'location', params[:location] %>
    <%= hidden_field_tag 'rankby', "distance" %><br>
    <%= submit_tag("Show me more fun stuff!", class: 'btn-primary') %>
    <% end %>
  </div>
</div>
<% end %>

app/views/excuses/index.html.erb
<div class="excuses">
  <h2><%= @excuses.sample %></h2><br>

  <a href="/excuses" class="btn btn-primary">Generate New Excuse</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaturEscape</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">NaturEscape</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-excuse"><%=link_to "Need an Excuse?", excuses_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <div class="btn-group">
          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </button>
          <div class="dropdown-menu">
            <li><%= link_to "My Account", dashboard_path %>
            <div class="dropdown-divider"></div>
            <li><%= link_to "Logout", signout_path %>
          </div>
        </div>
          <% else %>
          <li><%= link_to "Login with Google", google_login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <body>
    <%= yield %>
  </body>
  </html>

app/views/locations/show.html.erb
<% address = @location.results.first.formatted_address.split(",") %>
<% if params[:state] %>
<% lat = @location.results.first.geometry.bounds.northeast.lat.to_f %>
<% lng = @location.results.first.geometry.bounds.northeast.lng.to_f %>
<% else %>
<% lat = @location.results.first.geometry.location.lat %>
<% lng = @location.results.first.geometry.location.lng %>
<% end %>

<div id="container-fluid">
  <div class="location-info">
    <h1><%= address.first %></h1>
    <% address.each do |add| %>
    <%= add %><br>
    <% end %>
    <%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{@location.results.first.formatted_address}&zoom=13&size=400x400&
    markers=color:blue%7Clabel:S%7C11211%7C11206%7C11222&key=#{ENV['GOOGLE_API_KEY']}")%>
  </div>
</div>

<div id="activity-box">
  <div class="suggestions">
    <h1> What would you rather be doing?</h1>
    <%= form_tag("/alternative", method: "get") do %>
    <%= select_tag 'type', options_for_select(Activity.activities), class:'form-control' %>
    <%= hidden_field_tag 'location', "#{lat.to_f}, #{lng.to_f}" %>
    <%= hidden_field_tag 'rankby', "distance" %><br>
    <%= submit_tag("Show me the fun stuff!", class: 'btn-primary') %>
    <% end %>
  </div>
</div>

app/views/trails/index.html.erb
<h1 class="trail-header"> What outdoor area are your "friends" trying to take you? <h1>

<% trails = @trails.sort %>

<div id="trail-form">
<%= form_tag("/search", method: "get") do %>
<%= select_tag 'trail', options_for_select(trails), class:"form-control", id:"trail-bar" %>
<%= hidden_field_tag 'state', params[:state] %>
<%= submit_tag("Search", id:"dumb-button", class: 'btn btn-primary') %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="dashboard">
  <h1 class="header">Welcome, <%= current_user.first_name %>!</h1><br>

  <a href="/" class="btn btn-info" role="button">Home</a>
  <a href="/signout" class="btn btn-danger" role="button">Log Out</a>
</div>

app/views/welcome/index.html.erb
  <div id='welcome-form'>
  <h1 class="header">Welcome to NaturEscape</h1><br>

<h3 class="header"> Hate the outdoors, but someone has taken you there anyway? Let's find something fun to do nearby! </h3>
    <br><h3 class="header"> Where are you trying to escape from? </h3><br>

    <%= form_tag("/location", method: "get", class: "states-list") do %>
    <%= select_tag 'state', options_for_select(States.states_list), class:"form-control" %>
    <%= submit_tag("Search by State", class:'btn btn-primary') %>
    <% end %><br>
    <div class="header"> 
    OR<br>
  </div>

    <%= form_tag("/search", method: "get") do %>
    <%= hidden_field_tag(:q) %>
    <%= submit_tag("Search By Current Location", class:'btn btn-primary') %>
    <% end %>
  </div>